POST https://localhost:5001/api/inventoryProducts
content-type: application/json

{
  "vinmonopoletId": "3833001",
  "name": "Luisin Barolo Leon 2010",
  "fruit": "Nebbiolo 100%",
  "vintage": "2010",
  "price": 429,
  "country": "Piemonte",
  "productType": "Rødvin",
  "producer": "Moswines AS"
}

###
GET https://localhost:5001/api/inventoryProducts/3833001


###
GET https://localhost:5001/api/inventoryProducts

