version: "2.1"
services:
    postgres: 
        image: clkao/postgres-plv8
        container_name: postgres
        hostname: postgres
        environment:
            - variables.env
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - wine_network
        healthcheck:
          test: "pg_isready -U postgres"
          interval: 10s
          timeout: 5s
          retries: 5
    rabbitmq:
        container_name: rabbitmq
        image: "rabbitmq:3-management"
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            - wine_network
        healthcheck:
            test: ["CMD-SHELL", "if rabbitmqctl status; then \nexit 0 \nfi \nexit 1"]
            interval: 10s
            retries: 5
    migration: 
        build:
            dockerfile: src/Migration/Dockerfile
            context: .
        container_name: migration
        depends_on:
          postgres:
            condition: service_healthy
        networks:
            - wine_network
    web: 
        build:
            dockerfile: src/Web/Dockerfile
            context: .
        container_name: web
        ports:
            - "5000:5000"
        depends_on:
          postgres:
            condition: service_healthy
          rabbitmq:
            condition: service_healthy
          migration:
            condition: service_started
        networks:
            - wine_network
    messaging: 
        build:
            dockerfile: src/MessageEndpoint/Dockerfile
            context: .
        container_name: messaging
        depends_on:
          postgres:
            condition: service_healthy
          rabbitmq:
            condition: service_healthy
          migration:
            condition: service_started
        networks:
            - wine_network
networks:
  wine_network:
     driver: bridge
volumes:
    db-data: