# Build image
FROM microsoft/dotnet:2.1-sdk AS builder
WORKDIR /src

# Copy files
COPY . ./

RUN dotnet restore
RUN dotnet build

WORKDIR /src/Web
RUN dotnet publish -c Debug -o out

# Build runtime image
FROM microsoft/dotnet:2.1-sdk
WORKDIR /src
COPY --from=builder /src/Web/out .
ENV ASPNETCORE_URLS="http://*:5000"
ENTRYPOINT ["dotnet", "Web.dll"]